spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/medex"
    username: postgres
    password: root

data:
  mkb: "МКБ I48.1"
  section:
    header:
      drugs: "Назначенные препараты"
      contra: "Противопоказания"
      diag: "Клинический диагноз"
      exams: "Проведенные обследования"
      criteria: "Критерии качества"
      standard: "Стандарт лечения МКБ 148.1"
